---
- name: update the content 
  hosts: dev
  tasks:
    - name: UPdate the blue tag content
      ansible.builtin.copy:
        content: "Welcome to Blue Server"
        dest: /var/www/html/index.html 
      tags: [never,blue]
    - name: Update the green tag content
      ansible.builtin.copy:
        content: "Welcome to Green Server"
        dest: /var/www/html/index.html 
      tags: [never,green]
